### ISSUE TITLE
Not compatible with numpy>=1.12

### ISSUE THREAD

**Issue by grisaitis** [TuragaLab/malis#6]
Numpy 1.12 dropped support for indexing with floats: https://docs.scipy.org/doc/numpy-1.12.0/release.html#deprecationwarning-to-error

I think malis does this in seg_to_affgraph... I'll provide more details later

**Comment by hueifang** [comment]
Hi, I ran test_malis.py and got the following:

Traceback (most recent call last):
  File "test_malis.py", line 36, in <module>
    cc = m.connected_components(nVert,node1,node2,idxkeep)
  File "malis/malis.pyx", line 51, in malis.malis.connected_components
    (seg,segSizes) = prune_and_renum(seg,sizeThreshold)
  File "malis/malis.pyx", line 80, in malis.malis.prune_and_renum
    renum = np.zeros(int(segId.max()+1),dtype=np.uint64)
TypeError: 'numpy.float64' object cannot be interpreted as an integer

Numpy is 1.12.1. Do you have any idea as to how to fix it? Thanks!

**Comment by necrodancer** [comment]
I am suffering from the same problem as @hueifang for `test_malis.py`.
In the code as below:
```python
renum = np.zeros(int(segId.max()+1),dtype=np.uint64)
```
It looks like there is no problem since `segId.max()+1` is cast to integer.
But the error `TypeError: 'numpy.float64' object cannot be interpreted as an integer` occurs.
I think the error indicates that int() casting didn't work, or there is something wrong in higher version of Numpy. 

p.s. My Numpy version is 1.14.5.

**Comment by hueifang** [comment]
@necrodancer: You can resolve this issue by building from source: ./make.sh. It appeared that the pip would install an old version that has the type error.

**Comment by necrodancer** [comment]
@hueifang 
It worked after I built from `./make.sh'.
I really appreciate your comments. Thank you very much.


p.s. Should I close the issue?
Actually, this is the first time to ask sth in github.

**Comment by hueifang** [comment]
@necrodancer Glad it worked! 

ps. hmm... I don't know. It's my first time, too. :)

**Comment by necrodancer** [comment]
The Issue has been solved.
Closed #6.
