### ISSUE TITLE
Not compatible with scipy >=1.3.0

### ISSUE THREAD

**Issue by hanslovsky** [TuragaLab/malis#8]
SciPy had breaking changes (without increasing the major version!!!) and [previously deprecated aliases from `scipy.misc` were removed](https://docs.scipy.org/doc/scipy/reference/release.1.3.0.html#scipy-interpolate-changes):

```python
>>> import malis
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/hanslovskyp/my-experiment/0/conda-env/lib/python3.6/site-packages/malis/__init__.py", line 1, in <module>
    from .malis import *
  File "malis/malis.pyx", line 3, in init malis.malis
ImportError: cannot import name comb
```

Two possible solutions:
 1. Update all affected import statements and set minimum version requirement for scipy dependency
 2. Set upper bound for scipy dependency

I think (1) is a better solution. I currently do not have the time for a PR (maybe in three weeks), but this could be helpful for others who observe the same issue.

**Comment by Paragjain10** [comment]
the same thing is not working for me.

I installed scipy==1.3.0 but getting the same error

**Comment by hanslovsky** [comment]
@Paragjain10 try installing scipy<1.3.0

**Comment by Paragjain10** [comment]
Thank you, this worked

**Comment by Joohyeon-Jacob** [comment]
> @Paragjain10 try installing scipy<1.3.0

even after following the guide, still same error above occur. Anything else I could do?
From pip list, regarding scipy and scikit: 
```(road_seg_env_v2) greg@D-DS-0015:/media/HDD_4T/greg-workspace/transfered_code$ pip list | grep sci
scikit-image                0.19.3
scikit-learn                1.0.2
scipy                       1.2.3
