### ISSUE TITLE
Issue in building

### ISSUE THREAD

**Issue by QianChris** [TuragaLab/malis#9]
After 'pip install malis', see:
malis/malis_cpp.cpp(4): fatal error C1083: Cannot open include file: 'boost/pending/disjoint_sets.hpp': No such file or directory

**Comment by Haoxin22** [comment]
Hi Chris,

Have you solved it? I met the same issue as yours. Thanks!

> After 'pip install malis', see: malis/malis_cpp.cpp(4): fatal error C1083: Cannot open include file: 'boost/pending/disjoint_sets.hpp': No such file or directory

**Comment by liulianni1688** [comment]
I also encounter this issue and it has been solved.  Please try "python -m  pip install mails"

**Comment by liulianni1688** [comment]
Hello，I also encounter this problem:
you can install boost c++ library (https://www.boost.org/), and then link the library with malis code.

**Comment by dreamhasany** [comment]
@liulianni1688 Hello,can you explain how to link the library with malis code

**Comment by ysairaaj** [comment]
Hello , I encountered this error too . I extracted the boost files and pasted it in **C:\Program Files (x86)\Windows Kits\10\\include\10.0.22000.0\\winrt** . This solved the "No such file or directory " problem . However , I got a new error 

> Collecting malis
>   Using cached malis-1.0.tar.gz (7.0 kB)
>   Preparing metadata (setup.py) ... done
> Requirement already satisfied: cython in d:\anaconda\lib\site-packages (from malis) (0.29.35)
> Requirement already satisfied: numpy in d:\anaconda\lib\site-packages (from malis) (1.23.5)
> Requirement already satisfied: h5py in d:\anaconda\lib\site-packages (from malis) (3.7.0)
> Requirement already satisfied: scipy in d:\anaconda\lib\site-packages (from malis) (1.10.0)
> Building wheels for collected packages: malis
>   Building wheel for malis (setup.py) ... error
>   error: subprocess-exited-with-error
> 
>   × python setup.py bdist_wheel did not run successfully.
>   │ exit code: 1
>   ╰─> [86 lines of output]
>       running bdist_wheel
>       running build
>       running build_py
>       creating build
>       creating build\lib.win-amd64-cpython-310
>       creating build\lib.win-amd64-cpython-310\malis
>       copying malis\setup.py -> build\lib.win-amd64-cpython-310\malis
>       copying malis\test_malis.py -> build\lib.win-amd64-cpython-310\malis
>       copying malis\__init__.py -> build\lib.win-amd64-cpython-310\malis
>       running build_ext
>       cythoning malis/malis.pyx to malis\malis.cpp
>       D:\anaconda\lib\site-packages\Cython\Compiler\Main.py:369: FutureWarning: Cython directive 'language_level' not set, using 2 for now (Py2). This will change in a later release! File: C:\Users\hp\AppData\Local\Temp\pip-install-0445dqsf\malis_72140fde1c5b4c1fa11fface29426005\malis\malis.pyx
>         tree = Parsing.p_module(s, pxd, full_module_name)
>       building 'malis.malis' extension
>       creating build\temp.win-amd64-cpython-310
>       creating build\temp.win-amd64-cpython-310\Release
>       creating build\temp.win-amd64-cpython-310\Release\malis
>       "C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.36.32532\bin\HostX86\x64\cl.exe" /c /nologo /O2 /W3 /GL /DNDEBUG /MD -IC:\Users\hp\AppData\Local\Temp\pip-install-0445dqsf\malis_72140fde1c5b4c1fa11fface29426005\malis -ID:\anaconda -ID:\anaconda\include -ID:\anaconda\include -ID:\anaconda\Include -ID:\anaconda\lib\site-packages\numpy\core\include "-IC:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.36.32532\include" "-IC:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.36.32532\ATLMFC\include" "-IC:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Auxiliary\VS\include" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.22000.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22000.0\\um" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22000.0\\shared" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22000.0\\winrt" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22000.0\\cppwinrt" /EHsc /Tpmalis/malis_cpp.cpp /Fobuild\temp.win-amd64-cpython-310\Release\malis/malis_cpp.obj -std=c++11 -w
>       cl : Command line warning D9025 : overriding '/W3' with '/w'
>       cl : Command line warning D9002 : ignoring unknown option '-std=c++11'
>       malis_cpp.cpp
>       "C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.36.32532\bin\HostX86\x64\cl.exe" /c /nologo /O2 /W3 /GL /DNDEBUG /MD -IC:\Users\hp\AppData\Local\Temp\pip-install-0445dqsf\malis_72140fde1c5b4c1fa11fface29426005\malis -ID:\anaconda -ID:\anaconda\include -ID:\anaconda\include -ID:\anaconda\Include -ID:\anaconda\lib\site-packages\numpy\core\include "-IC:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.36.32532\include" "-IC:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.36.32532\ATLMFC\include" "-IC:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Auxiliary\VS\include" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.22000.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22000.0\\um" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22000.0\\shared" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22000.0\\winrt" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22000.0\\cppwinrt" /EHsc /Tpmalis\malis.cpp /Fobuild\temp.win-amd64-cpython-310\Release\malis\malis.obj -std=c++11 -w
>       cl : Command line warning D9025 : overriding '/W3' with '/w'
>       cl : Command line warning D9002 : ignoring unknown option '-std=c++11'
>       malis.cpp
>       D:\anaconda\lib\site-packages\numpy\core\include\numpy\npy_1_7_deprecated_api.h(14) : Warning Msg: Using deprecated NumPy API, disable it with #define NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION
>       Traceback (most recent call last):
>         File "<string>", line 2, in <module>
>         File "<pip-setuptools-caller>", line 34, in <module>
>         File "C:\Users\hp\AppData\Local\Temp\pip-install-0445dqsf\malis_72140fde1c5b4c1fa11fface29426005\setup.py", line 30, in <module>
>           setup(name='malis',
>         File "D:\anaconda\lib\site-packages\setuptools\__init__.py", line 87, in setup
>           return distutils.core.setup(**attrs)
>         File "D:\anaconda\lib\site-packages\setuptools\_distutils\core.py", line 185, in setup
>           return run_commands(dist)
>         File "D:\anaconda\lib\site-packages\setuptools\_distutils\core.py", line 201, in run_commands
>           dist.run_commands()
>         File "D:\anaconda\lib\site-packages\setuptools\_distutils\dist.py", line 969, in run_commands
>           self.run_command(cmd)
>         File "D:\anaconda\lib\site-packages\setuptools\dist.py", line 1208, in run_command
>           super().run_command(command)
>         File "D:\anaconda\lib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
>           cmd_obj.run()
>         File "D:\anaconda\lib\site-packages\wheel\bdist_wheel.py", line 325, in run
>           self.run_command("build")
>         File "D:\anaconda\lib\site-packages\setuptools\_distutils\cmd.py", line 318, in run_command
>           self.distribution.run_command(command)
>         File "D:\anaconda\lib\site-packages\setuptools\dist.py", line 1208, in run_command
>           super().run_command(command)
>         File "D:\anaconda\lib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
>           cmd_obj.run()
>         File "D:\anaconda\lib\site-packages\setuptools\_distutils\command\build.py", line 132, in run
>           self.run_command(cmd_name)
>         File "D:\anaconda\lib\site-packages\setuptools\_distutils\cmd.py", line 318, in run_command
>           self.distribution.run_command(command)
>         File "D:\anaconda\lib\site-packages\setuptools\dist.py", line 1208, in run_command
>           super().run_command(command)
>         File "D:\anaconda\lib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
>           cmd_obj.run()
>         File "D:\anaconda\lib\site-packages\setuptools\command\build_ext.py", line 84, in run
>           _build_ext.run(self)
>         File "D:\anaconda\lib\site-packages\Cython\Distutils\old_build_ext.py", line 186, in run
>           _build_ext.build_ext.run(self)
>         File "D:\anaconda\lib\site-packages\setuptools\_distutils\command\build_ext.py", line 346, in run
>           self.build_extensions()
>         File "D:\anaconda\lib\site-packages\Cython\Distutils\old_build_ext.py", line 195, in build_extensions
>           _build_ext.build_ext.build_extensions(self)
>         File "D:\anaconda\lib\site-packages\setuptools\_distutils\command\build_ext.py", line 468, in build_extensions
>           self._build_extensions_serial()
>         File "D:\anaconda\lib\site-packages\setuptools\_distutils\command\build_ext.py", line 494, in _build_extensions_serial
>           self.build_extension(ext)
>         File "D:\anaconda\lib\site-packages\setuptools\command\build_ext.py", line 246, in build_extension
>           _build_ext.build_extension(self, ext)
>         File "D:\anaconda\lib\site-packages\setuptools\_distutils\command\build_ext.py", line 573, in build_extension
>           self.compiler.link_shared_object(
>         File "D:\anaconda\lib\site-packages\setuptools\_distutils\ccompiler.py", line 751, in link_shared_object
>           self.link(
>         File "D:\anaconda\lib\site-packages\setuptools\_distutils\_msvccompiler.py", line 484, in link
>           lib_opts = gen_lib_options(self, library_dirs, runtime_library_dirs, libraries)
>         File "D:\anaconda\lib\site-packages\setuptools\msvc.py", line 230, in msvc14_gen_lib_options
>           return get_unpatched(msvc14_gen_lib_options)(*args, **kwargs)
>         File "D:\anaconda\lib\site-packages\setuptools\_distutils\ccompiler.py", line 1193, in gen_lib_options
>           lib_opts.append(compiler.library_dir_option(dir))
>         File "D:\anaconda\lib\site-packages\setuptools\_distutils\_msvccompiler.py", line 555, in library_dir_option
>           return "/LIBPATH:" + dir
>       TypeError: can only concatenate str (not "NoneType") to str
>       [end of output]
> 
>   note: This error originates from a subprocess, and is likely not a problem with pip.
>   ERROR: Failed building wheel for malis
>   Running setup.py clean for malis
> Failed to build malis
> Installing collected packages: malis
>   Running setup.py install for malis ... error
>   error: subprocess-exited-with-error
> 
>   × Running setup.py install for malis did not run successfully.
>   │ exit code: 1
>   ╰─> [88 lines of output]
>       running install
>       D:\anaconda\lib\site-packages\setuptools\command\install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
>         warnings.warn(
>       running build
>       running build_py
>       creating build
>       creating build\lib.win-amd64-cpython-310
>       creating build\lib.win-amd64-cpython-310\malis
>       copying malis\setup.py -> build\lib.win-amd64-cpython-310\malis
>       copying malis\test_malis.py -> build\lib.win-amd64-cpython-310\malis
>       copying malis\__init__.py -> build\lib.win-amd64-cpython-310\malis
>       running build_ext
>       skipping 'malis\malis.cpp' Cython extension (up-to-date)
>       building 'malis.malis' extension
>       creating build\temp.win-amd64-cpython-310
>       creating build\temp.win-amd64-cpython-310\Release
>       creating build\temp.win-amd64-cpython-310\Release\malis
>       "C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.36.32532\bin\HostX86\x64\cl.exe" /c /nologo /O2 /W3 /GL /DNDEBUG /MD -IC:\Users\hp\AppData\Local\Temp\pip-install-0445dqsf\malis_72140fde1c5b4c1fa11fface29426005\malis -ID:\anaconda -ID:\anaconda\include -ID:\anaconda\include -ID:\anaconda\Include -ID:\anaconda\lib\site-packages\numpy\core\include "-IC:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.36.32532\include" "-IC:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.36.32532\ATLMFC\include" "-IC:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Auxiliary\VS\include" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.22000.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22000.0\\um" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22000.0\\shared" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22000.0\\winrt" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22000.0\\cppwinrt" /EHsc /Tpmalis/malis_cpp.cpp /Fobuild\temp.win-amd64-cpython-310\Release\malis/malis_cpp.obj -std=c++11 -w
>       cl : Command line warning D9025 : overriding '/W3' with '/w'
>       cl : Command line warning D9002 : ignoring unknown option '-std=c++11'
>       malis_cpp.cpp
>       "C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.36.32532\bin\HostX86\x64\cl.exe" /c /nologo /O2 /W3 /GL /DNDEBUG /MD -IC:\Users\hp\AppData\Local\Temp\pip-install-0445dqsf\malis_72140fde1c5b4c1fa11fface29426005\malis -ID:\anaconda -ID:\anaconda\include -ID:\anaconda\include -ID:\anaconda\Include -ID:\anaconda\lib\site-packages\numpy\core\include "-IC:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.36.32532\include" "-IC:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.36.32532\ATLMFC\include" "-IC:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Auxiliary\VS\include" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.22000.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22000.0\\um" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22000.0\\shared" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22000.0\\winrt" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22000.0\\cppwinrt" /EHsc /Tpmalis\malis.cpp /Fobuild\temp.win-amd64-cpython-310\Release\malis\malis.obj -std=c++11 -w
>       cl : Command line warning D9025 : overriding '/W3' with '/w'
>       cl : Command line warning D9002 : ignoring unknown option '-std=c++11'
>       malis.cpp
>       D:\anaconda\lib\site-packages\numpy\core\include\numpy\npy_1_7_deprecated_api.h(14) : Warning Msg: Using deprecated NumPy API, disable it with #define NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION
>       Traceback (most recent call last):
>         File "<string>", line 2, in <module>
>         File "<pip-setuptools-caller>", line 34, in <module>
>         File "C:\Users\hp\AppData\Local\Temp\pip-install-0445dqsf\malis_72140fde1c5b4c1fa11fface29426005\setup.py", line 30, in <module>
>           setup(name='malis',
>         File "D:\anaconda\lib\site-packages\setuptools\__init__.py", line 87, in setup
>           return distutils.core.setup(**attrs)
>         File "D:\anaconda\lib\site-packages\setuptools\_distutils\core.py", line 185, in setup
>           return run_commands(dist)
>         File "D:\anaconda\lib\site-packages\setuptools\_distutils\core.py", line 201, in run_commands
>           dist.run_commands()
>         File "D:\anaconda\lib\site-packages\setuptools\_distutils\dist.py", line 969, in run_commands
>           self.run_command(cmd)
>         File "D:\anaconda\lib\site-packages\setuptools\dist.py", line 1208, in run_command
>           super().run_command(command)
>         File "D:\anaconda\lib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
>           cmd_obj.run()
>         File "D:\anaconda\lib\site-packages\setuptools\command\install.py", line 68, in run
>           return orig.install.run(self)
>         File "D:\anaconda\lib\site-packages\setuptools\_distutils\command\install.py", line 698, in run
>           self.run_command('build')
>         File "D:\anaconda\lib\site-packages\setuptools\_distutils\cmd.py", line 318, in run_command
>           self.distribution.run_command(command)
>         File "D:\anaconda\lib\site-packages\setuptools\dist.py", line 1208, in run_command
>           super().run_command(command)
>         File "D:\anaconda\lib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
>           cmd_obj.run()
>         File "D:\anaconda\lib\site-packages\setuptools\_distutils\command\build.py", line 132, in run
>           self.run_command(cmd_name)
>         File "D:\anaconda\lib\site-packages\setuptools\_distutils\cmd.py", line 318, in run_command
>           self.distribution.run_command(command)
>         File "D:\anaconda\lib\site-packages\setuptools\dist.py", line 1208, in run_command
>           super().run_command(command)
>         File "D:\anaconda\lib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
>           cmd_obj.run()
>         File "D:\anaconda\lib\site-packages\setuptools\command\build_ext.py", line 84, in run
>           _build_ext.run(self)
>         File "D:\anaconda\lib\site-packages\Cython\Distutils\old_build_ext.py", line 186, in run
>           _build_ext.build_ext.run(self)
>         File "D:\anaconda\lib\site-packages\setuptools\_distutils\command\build_ext.py", line 346, in run
>           self.build_extensions()
>         File "D:\anaconda\lib\site-packages\Cython\Distutils\old_build_ext.py", line 195, in build_extensions
>           _build_ext.build_ext.build_extensions(self)
>         File "D:\anaconda\lib\site-packages\setuptools\_distutils\command\build_ext.py", line 468, in build_extensions
>           self._build_extensions_serial()
>         File "D:\anaconda\lib\site-packages\setuptools\_distutils\command\build_ext.py", line 494, in _build_extensions_serial
>           self.build_extension(ext)
>         File "D:\anaconda\lib\site-packages\setuptools\command\build_ext.py", line 246, in build_extension
>           _build_ext.build_extension(self, ext)
>         File "D:\anaconda\lib\site-packages\setuptools\_distutils\command\build_ext.py", line 573, in build_extension
>           self.compiler.link_shared_object(
>         File "D:\anaconda\lib\site-packages\setuptools\_distutils\ccompiler.py", line 751, in link_shared_object
>           self.link(
>         File "D:\anaconda\lib\site-packages\setuptools\_distutils\_msvccompiler.py", line 484, in link
>           lib_opts = gen_lib_options(self, library_dirs, runtime_library_dirs, libraries)
>         File "D:\anaconda\lib\site-packages\setuptools\msvc.py", line 230, in msvc14_gen_lib_options
>           return get_unpatched(msvc14_gen_lib_options)(*args, **kwargs)
>         File "D:\anaconda\lib\site-packages\setuptools\_distutils\ccompiler.py", line 1193, in gen_lib_options
>           lib_opts.append(compiler.library_dir_option(dir))
>         File "D:\anaconda\lib\site-packages\setuptools\_distutils\_msvccompiler.py", line 555, in library_dir_option
>           return "/LIBPATH:" + dir
>       TypeError: can only concatenate str (not "NoneType") to str
>       [end of output]
> 
>   note: This error originates from a subprocess, and is likely not a problem with pip.
> error: legacy-install-failure
> 
> × Encountered error while trying to install package.
> ╰─> malis
> 
> note: This is an issue with the package mentioned above, not pip.
> hint: See above for output from the failure. 

Please can anyone help me with this issue??
